<a href="https://colab.research.google.com/github/renatagomezc/Actividad1.1-Extraccion-de-Datos/blob/main/Act1_2(Extraccion_de_datos).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [110]:
df= pd.read_excel('Datos de Facturacion limpio.xlsx')

In [111]:
df.head()

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10895 entries, 0 to 10894
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CVE_DOC        10895 non-null  object
 1   CVE_CLPV       10894 non-null  float64
 2   STATUS         10895 non-null  object
 3   CVE_VEND       10847 non-null  float64
 4   FECHAELAB      10895 non-null  datetime64[ns]
 5   FECHA_DOC      10895 non-null  datetime64[ns]
 6   FECHA_ENT      10893 non-null  object
 7   FECHA_VEN      10895 non-null  datetime64[ns]
 8   FECHA_CANCELA  358 non-null    datetime64[ns]
 9   CAN_TOT        10895 non-null  float64
 10  DES_TOT        10895 non-null  float64
 11  DES_FIN        10895 non-null  int64
dtypes: datetime64[ns](4), float64(4), int64(1), object(3)
memory usage: 1021.5+ KB

In [113]:
filtro1=df[(df["CVE_CLPV"] >= 1000) & (df["CVE_CLPV"]<=2000)]
filtro1

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
18,F29432,1965.0,C,2.0,2019-09-05 11:05:04.000,2019-09-05,2019-09-05 00:00:00,2019-09-20,2019-09-06,976.50,0.00,0
22,F29436,1965.0,C,2.0,2019-09-06 12:01:36.000,2019-09-06,2019-09-06 00:00:00,2019-09-21,2019-09-12,976.50,0.00,0
65,F29479,1240.0,E,2.0,2019-09-11 18:38:45.000,2019-09-11,2019-09-11 00:00:00,2019-09-11,NaT,4135.00,0.00,0
71,F29485,1965.0,C,2.0,2019-09-12 12:14:28.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,2019-09-12,976.50,146.48,0
72,F29486,1965.0,E,2.0,2019-09-12 12:25:52.000,2019-09-12,2019-09-12 00:00:00,2019-09-27,NaT,976.50,146.48,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10821,F40237,1757.0,E,2.0,2023-02-24 15:18:17.570,2023-02-24,2023-02-13 00:00:00,2023-02-24,NaT,10088.40,0.00,0
10839,F40255,1583.0,E,2.0,2023-02-28 09:15:45.753,2023-02-28,2023-02-28 00:00:00,2023-03-30,NaT,3467.35,0.00,0
10845,F40261,1786.0,E,2.0,2023-02-28 11:15:32.527,2023-02-28,2023-03-03 00:00:00,2023-02-28,NaT,4663.80,0.00,0
10871,F40287,1453.0,E,1.0,2023-03-01 12:58:23.397,2023-03-01,2023-02-27 00:00:00,2023-03-31,NaT,9000.00,0.00,0
10876,F40292,1082.0,E,6.0,2023-03-02 11:00:54.770,2023-03-02,2023-03-01 00:00:00,2023-03-02,NaT,3262.00,0.00,0

In [114]:
filtro2 = df[~(df["CVE_VEND"] == 5.0 ) & ~(df["CVE_VEND"] == 4.0)]
filtro2

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218.0,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [115]:
filtro3=df[df["FECHA_ENT"] == '2022-28-2']
filtro3

Empty DataFrame
Columns: [CVE_DOC, CVE_CLPV, STATUS, CVE_VEND, FECHAELAB, FECHA_DOC, FECHA_ENT, FECHA_VEN, FECHA_CANCELA, CAN_TOT, DES_TOT, DES_FIN]
Index: []

In [116]:
filtro4=df[(df["CAN_TOT"] < 5951.7)| (df["STATUS"] == "E")]
filtro4

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
0,F29414,2465.0,C,1.0,2019-09-03 08:58:42.000,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1,F29415,3926.0,C,1.0,2019-09-03 09:55:14.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
2,F29416,3926.0,C,1.0,2019-09-03 13:25:33.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
3,F29417,3926.0,C,1.0,2019-09-03 13:33:23.000,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
4,F29418,6813.0,C,2.0,2019-09-03 14:23:45.000,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10890,F40306,8842.0,E,2.0,2023-03-06 16:09:39.013,2023-03-06,2023-03-01 00:00:00,2023-03-06,NaT,3272.00,0.0,0
10891,F40307,6218.0,E,2.0,2023-03-06 16:38:42.933,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,504.15,0.0,0
10892,F40308,5926.0,E,2.0,2023-03-06 17:02:33.390,2023-03-06,2023-03-06 00:00:00,2023-03-06,NaT,275.68,0.0,0
10893,F40309,361.0,E,2.0,2023-03-07 12:43:49.567,2023-03-07,2023-03-07 00:00:00,2023-03-07,NaT,129.30,0.0,0
10894,F40310,3011.0,E,2.0,2023-03-07 12:45:58.407,2023-03-07,2023-03-01 00:00:00,2023-03-07,NaT,517.20,0.0,0

In [117]:
filtro5 = df.iloc[ : , [0, 6, 7,9]]  
filtro5

      CVE_DOC            FECHA_ENT  FECHA_VEN  CAN_TOT
0      F29414  2019-09-03 00:00:00 2019-09-18  3980.00
1      F29415  2019-09-03 00:00:00 2019-10-03  1550.00
2      F29416  2019-09-03 00:00:00 2019-10-03  1550.00
3      F29417  2019-09-03 00:00:00 2019-10-03  1550.00
4      F29418  2019-09-03 00:00:00 2019-09-03  2435.44
...       ...                  ...        ...      ...
10890  F40306  2023-03-01 00:00:00 2023-03-06  3272.00
10891  F40307  2023-03-06 00:00:00 2023-03-06   504.15
10892  F40308  2023-03-06 00:00:00 2023-03-06   275.68
10893  F40309  2023-03-07 00:00:00 2023-03-07   129.30
10894  F40310  2023-03-01 00:00:00 2023-03-07   517.20

[10895 rows x 4 columns]

In [118]:
filtro6 = df.iloc[7001:7099, :  ] 
filtro6

,CVE_DOC,CVE_CLPV,STATUS,CVE_VEND,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
7001,F36417,5271.0,E,3.0,2021-10-15 08:40:29.183,2021-10-15,2021-10-06 00:00:00,2021-11-14,NaT,8555.24,0.0,0
7002,F36418,5746.0,E,2.0,2021-10-15 08:51:03.463,2021-10-15,2021-10-14 00:00:00,2021-10-15,NaT,620.77,0.0,0
7003,F36419,2163.0,E,3.0,2021-10-15 08:56:23.280,2021-10-15,2021-10-15 00:00:00,2021-10-15,NaT,560.00,0.0,0
7004,F36420,1429.0,E,1.0,2021-10-15 09:01:08.393,2021-10-15,2021-10-15 00:00:00,2021-12-14,NaT,23625.00,0.0,0
7005,F36421,5039.0,E,1.0,2021-10-15 09:07:07.103,2021-10-15,2021-10-08 00:00:00,2022-01-13,NaT,3308.78,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7094,F36510,4480.0,E,2.0,2021-10-27 13:01:57.527,2021-10-27,2021-10-21 00:00:00,2021-11-11,NaT,2904.40,0.0,0
7095,F36511,4480.0,E,2.0,2021-10-27 13:07:43.223,2021-10-27,2021-10-27 00:00:00,2021-11-11,NaT,1137.50,0.0,0
7096,F36512,8186.0,E,2.0,2021-10-27 13:22:23.980,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,94.84,0.0,0
7097,F36513,4403.0,E,2.0,2021-10-27 13:35:40.677,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,847.00,0.0,0
7098,F36514,5589.0,E,2.0,2021-10-27 14:02:54.630,2021-10-27,2021-10-27 00:00:00,2021-10-27,NaT,965.00,0.0,0

In [119]:
df1= pd.read_excel('Datos de Facturación.xlsx', index_col=3)
df1.head()

,CVE_DOC,CVE_CLPV,STATUS,FECHAELAB,FECHA_DOC,FECHA_ENT,FECHA_VEN,FECHA_CANCELA,CAN_TOT,DES_TOT,DES_FIN
CVE_VEND,,,,,,,,,,,
1.0,F29414,2465,C,2019-09-03 08:58:42,2019-09-03,2019-09-03 00:00:00,2019-09-18,2019-09-04,3980.00,0.0,0
1.0,F29415,3926,C,2019-09-03 09:55:14,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
1.0,F29416,3926,C,2019-09-03 13:25:33,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-03,1550.00,0.0,0
1.0,F29417,3926,C,2019-09-03 13:33:23,2019-09-03,2019-09-03 00:00:00,2019-10-03,2019-09-17,1550.00,0.0,0
2.0,F29418,6813,C,2019-09-03 14:23:45,2019-09-03,2019-09-03 00:00:00,2019-09-03,2019-09-10,2435.44,0.0,0

In [120]:
filtro7=df1.loc[[1.0,2.0], ["FECHAELAB"]]
filtro7

                       FECHAELAB
CVE_VEND
1.0      2019-09-03 08:58:42.000
1.0      2019-09-03 09:55:14.000
1.0      2019-09-03 13:25:33.000
1.0      2019-09-03 13:33:23.000
1.0      2019-09-04 09:15:12.000
...                          ...
2.0      2023-03-06 16:09:39.013
2.0      2023-03-06 16:38:42.933
2.0      2023-03-06 17:02:33.390
2.0      2023-03-07 12:43:49.567
2.0      2023-03-07 12:45:58.407

[8665 rows x 1 columns]

In [121]:
filtro1.to_csv("Entregable1.1.csv")
filtro2.to_csv("Entregable2.1.csv")
filtro3.to_csv("Entregable3.1.csv")
filtro4.to_csv("Entregable4.1.csv")
filtro5.to_csv("Entregable5.1.csv")
filtro6.to_csv("Entregable6.1.csv")
filtro7.to_csv("Entregable7.1.csv")

In [122]:
from google.colab import files 
  
  
files.download("Entregable1.1.csv")
files.download("Entregable2.1.csv")
files.download("Entregable3.1.csv")
files.download("Entregable4.1.csv")
files.download("Entregable5.1.csv")
files.download("Entregable6.1.csv")